/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author judie
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bluepanel = new javax.swing.JPanel();
        whitepanel = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblTotalExpense = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblExpense = new javax.swing.JLabel();
        lblTotalIncome = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnIncome = new javax.swing.JButton();
        btnExpense = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbl8 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lbl10 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 147, 179));

        bluepanel.setBackground(new java.awt.Color(52, 64, 116));
        bluepanel.setPreferredSize(new java.awt.Dimension(722, 300));

        whitepanel.setBackground(new java.awt.Color(255, 255, 255));

        lbl1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lbl1.setForeground(new java.awt.Color(219, 147, 180));
        lbl1.setText("BALANCE:");

        lblIncome.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(219, 147, 180));
        lblIncome.setText("INCOME");

        lblTotalExpense.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTotalExpense.setForeground(new java.awt.Color(219, 147, 180));
        lblTotalExpense.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalExpense.setText("...");

        lblBalance.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(219, 147, 180));
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("....");

        lblExpense.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblExpense.setForeground(new java.awt.Color(219, 147, 180));
        lblExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpense.setText("EXPENSE");

        lblTotalIncome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTotalIncome.setForeground(new java.awt.Color(219, 147, 180));
        lblTotalIncome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalIncome.setText("...");

        javax.swing.GroupLayout whitepanelLayout = new javax.swing.GroupLayout(whitepanel);
        whitepanel.setLayout(whitepanelLayout);
        whitepanelLayout.setHorizontalGroup(
            whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitepanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(whitepanelLayout.createSequentialGroup()
                        .addComponent(lblIncome)
                        .addGap(47, 47, 47)
                        .addComponent(lblTotalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitepanelLayout.createSequentialGroup()
                        .addComponent(lblExpense)
                        .addGap(47, 47, 47)
                        .addComponent(lblTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        whitepanelLayout.setVerticalGroup(
            whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitepanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncome)
                    .addComponent(lblTotalExpense)
                    .addComponent(lblExpense)
                    .addComponent(lblTotalIncome))
                .addGap(12, 12, 12))
        );

        lbl2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(219, 147, 180));
        lbl2.setText("ADD TRANSACTION");

        btnIncome.setBackground(new java.awt.Color(242, 242, 242));
        btnIncome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnIncome.setForeground(new java.awt.Color(219, 147, 180));
        btnIncome.setText("INCOME");
        btnIncome.setBorderPainted(false);
        btnIncome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncome.setInheritsPopupMenu(true);
        btnIncome.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeActionPerformed(evt);
            }
        });

        btnExpense.setBackground(new java.awt.Color(242, 242, 242));
        btnExpense.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnExpense.setForeground(new java.awt.Color(219, 147, 180));
        btnExpense.setText("EXPENSE");
        btnExpense.setBorderPainted(false);
        btnExpense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpense.setInheritsPopupMenu(true);
        btnExpense.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenseActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(242, 242, 242));
        btnDelete.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(219, 147, 180));
        btnDelete.setText("DELETE");
        btnDelete.setBorderPainted(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(242, 242, 242));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(219, 147, 180));
        btnEdit.setText("EDIT");
        btnEdit.setBorderPainted(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setInheritsPopupMenu(true);
        btnEdit.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbl8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbl8.setForeground(new java.awt.Color(219, 147, 180));
        lbl8.setText("Name:");

        txtCategory.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtCategory.setForeground(new java.awt.Color(219, 147, 180));

        lbl9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbl9.setForeground(new java.awt.Color(219, 147, 180));
        lbl9.setText("Amount:");

        txtAmount.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(219, 147, 180));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        lbl10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbl10.setForeground(new java.awt.Color(219, 147, 180));
        lbl10.setText("Date:");

        javax.swing.GroupLayout bluepanelLayout = new javax.swing.GroupLayout(bluepanel);
        bluepanel.setLayout(bluepanelLayout);
        bluepanelLayout.setHorizontalGroup(
            bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bluepanelLayout.createSequentialGroup()
                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluepanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lbl2))
                    .addGroup(bluepanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bluepanelLayout.createSequentialGroup()
                                .addComponent(btnIncome)
                                .addGap(18, 18, 18)
                                .addComponent(btnExpense)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit))
                            .addGroup(bluepanelLayout.createSequentialGroup()
                                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl9)
                                    .addComponent(lbl10)
                                    .addComponent(lbl8))
                                .addGap(18, 18, 18)
                                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bluepanelLayout.setVerticalGroup(
            bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluepanelLayout.createSequentialGroup()
                .addComponent(whitepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncome)
                    .addComponent(btnExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bluepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl10)
                .addGap(136, 136, 136))
        );

        lbl6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 26)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("TRANSACTION HISTORY");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTable1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Date", "Amount"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(219, 147, 180));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bluepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl6)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncomeActionPerformed

    private void btnExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenseActionPerformed

    }//GEN-LAST:event_btnExpenseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bluepanel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExpense;
    private javax.swing.JButton btnIncome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblExpense;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblTotalExpense;
    private javax.swing.JLabel lblTotalIncome;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JPanel whitepanel;
    // End of variables declaration//GEN-END:variables
}
